Gaussian Elimination Algorithm 

In [ ]:
import numpy as np 

# Function Swap Rows

# This funtion has a input array and two indexes to swap the rows corresponding to those indexes
# It does not change the matrix but returns a new One

def swap_rows(M,row_index_1,row_index_2):
    """
    Swap rows in the given matrix.

    Parameters:
    - matrix (numpy.array): The input matrix to perform row swaps on.
    - row_index_1 (int): Index of the first row to be swapped.
    - row_index_2 (int): Index of the second row to be swapped.
    """

    # Copy matrix M so the changes do not affect the original matrix. 
    M = M.copy()
    # Swap indexes
    M[[row_index_1, row_index_2]] = M[[row_index_2, row_index_1]]
    return M



M = np.array([[1,3,6],
               [0,-5,2],
               [-4,5,8]])

print(M)

M_swapped = swap_rows(M,0,2)
print(M_swapped)


# Finding the first non-zero value in a column starting from a specific value



[[ 1  3  6]
 [ 0 -5  2]
 [-4  5  8]]
[[-4  5  8]
 [ 0 -5  2]
 [ 1  3  6]]
