Gaussian Elimination Algorithm 

In [18]:
import numpy as np 

# Function Swap Rows

# This funtion has a input array and two indexes to swap the rows corresponding to those indexes
# It does not change the matrix but returns a new One

def swap_rows(M,row_index_1,row_index_2):
    """
    Swap rows in the given matrix.

    Parameters:
    - matrix (numpy.array): The input matrix to perform row swaps on.
    - row_index_1 (int): Index of the first row to be swapped.
    - row_index_2 (int): Index of the second row to be swapped.
    """

    # Copy matrix M so the changes do not affect the original matrix. 
    M = M.copy()
    # Swap indexes
    M[[row_index_1, row_index_2]] = M[[row_index_2, row_index_1]]
    return M



M = np.array([[1,3,6],
               [0,-5,2],
               [-4,5,8]])

print("\n",M)

M_swapped = swap_rows(M,0,2)
print("\n",M_swapped)


# Finding the first non-zero value in a column starting from a specific value

def get_index_first_non_zero_value_from_column(M,starting_Row,column):
    column_array = M[starting_Row:,column]
    
    for i, val in enumerate(column_array):
        if not np.isclose(val,0,atol=1e-5):
            index = i + starting_Row
            return index
     
        
    return -1
    

# Practice Question for getting Column containing non zero value

N = np.array([
    [0,5,-3,6,8],
    [0,6,3,8,1],
    [0,0,0,0,0],
    [0,0,0,0,7],
    [0,2,1,0,4]
])

print("\n",N)

print("checking it returns -1")
print(get_index_first_non_zero_value_from_column(N,column=0,starting_Row=0))

print("Checking it returns 0")

print(get_index_first_non_zero_value_from_column(N,starting_Row=3,column=4))




def get_index_first_non_zero_value_from_row(M,row,Augmented = False):
    
    M=M.copy()
    if Augmented == True:
        M=M[:,:-1]
        
        
    # Get the Desired Row
    get_row=M[row]
    
    
    for i, val in enumerate(get_row):
        if not np.isclose(val,0,atol=1e-5):
            return i
    
    return -1


        
print(get_index_first_non_zero_value_from_row(N,2))
print(get_index_first_non_zero_value_from_row(N,4))
print(get_index_first_non_zero_value_from_row(N,3))
print(get_index_first_non_zero_value_from_row(N,3,Augmented=True))
        
        
        
        
# How to create Augmented Matrix 
# This is done by using Horizontally stack two matrices

def AugmentedMatrix(A,B):
    
    augmentedMatrix=np.hstack((A,B))
    return augmentedMatrix
            
            
            
A = np.array([[3,2,1],
              [4,6,7],
              [8,8,9]])

B = np.array([[2],[5],[6]])


getAugmentedMatrix = AugmentedMatrix(A,B)
print(getAugmentedMatrix)



# Row Echelon Form Implementation

def Row_Echelon(A,B):
    
    det_A = np.linalg.det(A)
    
    if np.isclose(det_A,0):
        return "Singular System"
    
    
    A = A.copy()
    B = B.copy()
    
    A = A.astype(float)
    B = B.astype(float)
    
    num_rows= len(A)
    
    M = AugmentedMatrix(A,B)
    
    
    for row in range(num_rows):
        pivot_candidate=M[row,row]
        
        if np.isclose(pivot_candidate,0,atol=1e-5):
            first_non_zero_value_below_pivot=get_index_first_non_zero_value_from_column(M,row,row)
            
            M = swap_rows(M,row,first_non_zero_value_below_pivot)
            
            pivot = M[row,row]
            
        else:
            pivot = pivot_candidate
            

        M[row] = (1/pivot) * M[row]
    
    for j in range(row+1,num_rows):
        value_below_pivot = M[j,row]
        
    
    return M        
        
        
# Testing

A = np.array([[1,2,3],[0,1,0], [0,0,5]])
B = np.array([[1], [2], [4]])
Row_Echelon(A,B)



def backSubstitution(M):
    M = M.copy()
    
    num_rows=np.shape[0]
    
    for row in reversed(range(num_rows)):
        substitution_row=num_rows
 
        index = get_index_first_non_zero_value_from_row(M, row, augmented=True)        
        
    
    for j in range(row):
               
        row_to_reduce = M[j]
        
        value = row_to_reduce[index]
        
        row_to_reduce = row_to_reduce - value * M[row]
        
        M[j,:] = row_to_reduce
        
    
    solution = M[:,-1]
    
    return solution
    
    
            
        
            
            



 [[ 1  3  6]
 [ 0 -5  2]
 [-4  5  8]]

 [[-4  5  8]
 [ 0 -5  2]
 [ 1  3  6]]

 [[ 0  5 -3  6  8]
 [ 0  6  3  8  1]
 [ 0  0  0  0  0]
 [ 0  0  0  0  7]
 [ 0  2  1  0  4]]
checking it returns -1
-1
Checking it returns 0
3
-1
1
4
-1
[[3 2 1 2]
 [4 6 7 5]
 [8 8 9 6]]
