In [1]:
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


Another way of implementing Array using arange method


In [6]:
# Create an array with 3 integers 
import numpy as np
b = np.arange(3)
print(b)


# We can create an array using arange function in which three paramters are passed
# 1. The starting value then end value and last para is step how much step you want to add 

c = np.arange(1,20,3)
print(c)

# We have an another method called linspace it take same parameter but its job is different
# if we want to divide an array into x evenly spaces then we use this method
# default is float values np.float64

d = np.linspace(0,100,5)
print(d)

# we can change its datatype to int we have a attribute dtype = ?

e = np.linspace(0,100,5,dtype = int)
print(e)

[0 1 2]
[ 1  4  7 10 13 16 19]
[  0.  25.  50.  75. 100.]
[  0  25  50  75 100]


Built in Methods

In [10]:
import numpy as np

# ones, zeros, empty and random
# these 4 methods always required one paramter

a = np.ones(3,dtype= int)
b = np.zeros(3, dtype = int)
c = np.empty(3, dtype= int)
d = np.random.rand(3)

print(a)
print(b)
print(c)
print(d)

[1 1 1]
[0 0 0]
[0 0 0]
[0.85640613 0.70172998 0.3790588 ]


Multi Dimensional Array

In [16]:
# There are different ways to create multi dimensional array
# first is simple one

a = np.array([[3,2,1],[4,5,6]])
print(a)

# second one is reshaping
b = np.array([1,2,3,4,5,6])

multi_Dimension= np.reshape(b,
                            (2,3)
                            )
print(multi_Dimension)

# we can store the size, shape and dimension

size = multi_Dimension.size
shape = multi_Dimension.shape
dimension = multi_Dimension.ndim

print("The size of the array is ",size)
print("The shape of the array is ",shape)
print("The Dimension of the array is ",dimension)


[[3 2 1]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
The size of the array is  6
The shape of the array is  (2, 3)
The Dimension of the array is  2


Array Math Operation

In [18]:
# There are multiple operations we can perform

import numpy as np


arr1= np.array([1,2,3])
arr2 = np.array([3,4,6])

addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2

print("Addition")
print(addition)
print("Subtraction")
print(subtraction)
print("Multiplication")
print(multiplication)

# we can multiply a scalar with a vector


vector = np.array([1,2])
vector = vector * 1.6
print(vector)

Addition
[4 6 9]
Subtraction
[-2 -2 -3]
Multiplication
[ 3  8 18]
[1.6 3.2]


Indexing

In [21]:
# indexing we can select any index and print whatever it takes

import numpy as np

a = np.array([1,2,3])
print(a[0])


# for multi Dimensional we can go for i,j indice

b = np.array([[1,2,4],
              [6,8,3]])

print(b[1][1])

1
8


Slicing

In [22]:
# Slicing gives you a sublist of elements that you specify from the array. The slice notation 
# specifies a start and end value, and copies the list from start up to but not including the end (end-exclusive).

# The syntax is:

# array[start:end:step]

# If no value is passed to start, it is assumed start = 0, if no value is passed for end, 
# it is assumed that end = length of array and if no value is passed to step, it is assumed step = 1.


a = np.array([2,5,8,1,6,9])

slice_array= a[:4]
print(slice_array)

[2 5 8 1]


Stacking

In [25]:
import numpy as np

a1 = np.array([[1,2],
               [3,4]])

a2 = np.array([[5,6],[8,9]])

# vertical takes only one argument
vertical_Stack= np.vstack((a1,a2))
print(vertical_Stack)

# horizontal takes only one argument

horizontal_stack = np.hstack((a1,a2))
print(horizontal_stack)


[[1 2]
 [3 4]
 [5 6]
 [8 9]]
[[1 2 5 6]
 [3 4 8 9]]
